baseURL = "https://arjunaanand.github.io"
title = "Alexa Wonders"
copyright = "Copyright © 2021, Arjuna Anand"
languageCode = "en-US"
theme = "indigo"

[params]
  Author = "Arjuna Anand"
  Description = "Alexa Wonders"
  Subtitle = "Alexa Wonders For You"
  Avatar = "images/site-logo.svg"
  Biography = "A short description, a few sentences describing the author. Set the 'ShowBio' parameter to false to hide this."
  ShowBio = false
  PermalinkText = "🔗"
  mainSections = ["post"]

  # Contact/social-network identifiers for social icons
  EmailAddress = "anandhianandmust@gmail.com"
  GitHubUser = "arjunaanand"
  MediumUser = "anandhianandmust"
  TwitterUser = "arjunaanand99"

  # These are parameters used for indieweb identity. You should set these along
  # with the above email/social network parameters.
  [params.indieWeb]  
    EmailAddress = "anandhianandmust@gmail.com"
	GitHubUser = "arjunaanand"
	MediumUser = "anandhianandmust"
	TwitterUser = "arjunaanand99"
    Country = "India"
    City = "Bengaluru"

  [params.endpoints]
    Auth = "https://indieauth.com/auth"
    Token = "https://tokens.indieauth.com/token"
    # To get webmention support, just register at webmention.io and paste the link for endpoint here.
    #Webmention = "https://webmention.io/<yourusername>/webmention"
    # To get micropub support, you'll need to install a Micropub endpoint at your site and put its link there.
    # To get an endpoint with Hugo support, use nanopub: https://github.com/dg01d/nanopub
    # It will probably require some PHP hackery though, as it's fairly basic.
    #Micropub = ""
    # To get microsub support, you can use Aperture from p3k. Either go to https://aperture.p3k.io or self-host it (it's open source!)
    #Microsub = ""